### PR TITLE
Preetwinder python modernize

### PR DESCRIPTION
**Pull request by redapple**
Based on https://github.com/scrapinghub/frontera/pull/168#issuecomment-233292482
Testing Python 3 tests on Travis CI to see where we're at

### CODE REVIEW

**Comment by Preetwinder** [comment]
I don't know why ZeroMQ tests are failing for Python 2 but I think the MySQL tests can be fixed by explicitly specifying the DBAPI in https://github.com/scrapinghub/frontera/blob/master/tests/contrib/backends/sqlalchemy/test_backend_sqlalchemy.py.  
DB_ENGINE = 'mysql+pymysql://travis:@localhost/backend_test'

**Comment by redapple** [comment]
You can merge this branch into your PR #168 branch (`python-modernize`), and continue in https://github.com/scrapinghub/frontera/pull/168

**Comment by redapple** [comment]
Or incorporate the changes, they're very small

**Comment by redapple** [comment]
I'll close this one. Let's continue in https://github.com/scrapinghub/frontera/pull/168

**Pull request closed without merging**
