### PR TITLE
[RFC] Better OverusedBuffer implementation

### PR DESCRIPTION
**Pull request by ZipFile**
Well, why not? Won't harm while we're in search of the proper solution.

Tests located at `tests/test_core_overused_buffer.py`.

### CODE REVIEW

**Comment by sibiryakov** [comment]
We need a test case for this.

**Comment by sibiryakov** [comment]
Well done!
If you're looking around OverusedBuffer let's think about reliability. There is no protection from excessive memory consumption. I propose to introduce some setting designating memory limit of OverusedBuffer and another option selecting the type of behavior when memory consumption has reached the limit.
I see two possible strategies:
 - Dropping requests. We should do it the balanced way, e.g. not to drop a single domain, rather drop equal amount from all domains, always logging with WARN level how much was dropped and with DEBUG what exactly was dropped.
 - Stop querying storage backend. Again logging that memory limit was reached, and OB is now using only it's internal storage.

let me know what do you think

**Comment by ZipFile** [comment]
Hello.

Sounds wise enough. I'd like to add third behaviour: do nothing (for debugging purposes). But I think it's task for separate PR.

Also there is a problem how to find memory usage. Should it be like "max n requsts per host in a buffer" or should it be something that mess with python internals like 'sys.getsizeof'?

**Comment by sibiryakov** [comment]
> Also there is a problem how to find memory usage. Should it be like "max n requsts per host in a buffer" or should it be something that mess with python internals like 'sys.getsizeof'?
I think first one, or it could be max number of requests in OB.

**Comment by sibiryakov** [comment]
what [rfc] in the title means?

**Comment by voith** [comment]
Request for Comments?

**Comment by sibiryakov** [comment]
Hey @ZipFile is it ready for merge?

**Comment by ZipFile** [comment]
Yeah, sure.

**Comment by sibiryakov** [comment]
Thanks 🍺 
do you think it's going to be more efficient from performance prospective @ZipFile ?

**Comment by ZipFile** [comment]
There won't be lots of gain, but overall performance should improve a bit.

According to [research on the net ](http://stackoverflow.com/a/12556053) inserting items to the buffer will definitely improve. As of popping up from the buffer, I believe, removing extra calls and checks might do the trick.

**Pull request merged**
