### PR TITLE
Converter should pass scrapy body in Request

### PR DESCRIPTION
**Pull request by markbaas**

### CODE REVIEW

**Comment by sibiryakov** [comment]
Hey @markbaas! Thanks for PR. 
You meant POST type requests?

**Comment by markbaas** [comment]
Yes this affects POST request.

**Comment by sibiryakov** [comment]
That makes sense to me. Could you please write a test case? Any documentation update is needed?

**Comment by sibiryakov** [comment]
Hey @markbaas any update on this?

**Comment by sibiryakov** [comment]
IMO, the right thing to do is to add body field in Frontera's Request object and add it to SQLAlchemy backend as a separate field in DB.

**Comment by kalessin** [comment]
Actually there is a separate repo, https://github.com/scrapinghub/scrapy-frontera which is exclusively for scrapy usage of frontera. We don't need anymore any PR related to scrapy.

**Comment by sibiryakov** [comment]
This patch is useful for Frontera, so I'm reopening it just not to forget about this feature.

**Comment by markbaas** [comment]
@sibiryakov I will get you the test case as soon as possible.

**Comment by markbaas** [comment]
@sibiryakov tests done!

**Comment by sibiryakov** [comment]
Thanks @markbaas! What do you think about moving body content to separate field in ``Request`` object? I like this idea a lot, because it will help keep the meta contents light-weight. NP, If you don't have time for that.

**Comment by markbaas** [comment]
That'd indeed be better. I'll get it done when I get some time.

**Comment by markbaas** [comment]
Hey @sibiryakov, Sorry it took so long! What about this new code?

**Comment by sibiryakov** [comment]
Hey @markbaas It looks good! Please rebase the branch. Anything else you want to add?

**Comment by sibiryakov** [comment]
:thumbsup: :beers:

**Pull request merged**
