### PR TITLE
Added tests for FileSeedLoader and S3SeedLoader

### PR DESCRIPTION
**Pull request by voith**
Also removed an unused import

### CODE REVIEW

**Comment by voith** [comment]
A possible way to test `S3SeedLoader` would be:

```python
import mock
import os
import unittest
from shutil import rmtree
from tempfile import mkdtemp

from scrapy.spiders import Spider

from frontera.settings import Settings
from frontera.contrib.scrapy.middlewares.seeds.s3 import S3SeedLoader


class TestS3SeedLoader(unittest.TestCase):

    def setUp(self):
        settings = Settings()
        settings.SEEDS_SOURCE = 's3://some-bucket/seeds-folder'
        settings.SEEDS_AWS_ACCESS_KEY = 'access_key'
        settings.SEEDS_AWS_SECRET_ACCESS_KEY = 'secret_key'
        crawler = type('crawler', (object,), {})
        crawler.settings = settings
        self.seed_loader = S3SeedLoader(crawler)

    @mock.patch('frontera.contrib.scrapy.middlewares.seeds.s3.connect_s3')
    def test_process_start_requests(self, mock_connect_s3):
        tmp_path = mkdtemp()
        seed_path_1 = os.path.join(tmp_path, 'seeds1.txt')
        seed_path_2 = os.path.join(tmp_path, 'seeds2.txt')
        s1_content = """
https://www.example.com
https://www.scrapy.org
"""
        s2_content = """
https://www.dmoz.org
https://www.test.com
"""

        with open(seed_path_1, 'wb') as tmpl_file:
            tmpl_file.write(s1_content.encode('utf-8'))
        with open(seed_path_2, 'wb') as tmpl_file:
            tmpl_file.write(s2_content.encode('utf-8'))

        with open(seed_path_1, 'rU') as s1:
            with open(seed_path_2, 'rU') as s2:
                def mocked_connect_s3(*args, **kwargs):
                    class MockConnection(object):
                        def get_bucket(self, bucket_name):
                            class MockBucket(object):
                                def list(self, key):
                                    class MockKey(object):
                                        def __init__(self, name):
                                            self.name = name

                                        def get_contents_as_string(self, encoding):
                                            class Content(object):
                                                def __init__(self, obj):
                                                    self.obj = obj

                                                def split(self):
                                                    return self.obj

                                            if self.name == 'seeds1.txt':
                                                return Content(s1)
                                            else:
                                                return Content(s2)
                                    return [MockKey('seeds1.txt'), MockKey('seeds2.txt')]
                            return MockBucket()
                    return MockConnection()
                mock_connect_s3.side_effect = mocked_connect_s3
                requests = self.seed_loader.process_start_requests(None, Spider(name='spider'))
                self.assertEqual([r.url for r in requests],
                                 ['https://www.example.com', 'https://www.scrapy.org',
                                  'https://www.dmoz.org', 'https://www.test.com'])
        rmtree(tmp_path)

if __name__ == '__main__':
    unittest.main()

```
But this requires modules `mock` and `boto` to be installed. @sibiryakov If you approve the installation of these modules than I can add this test too as part of this PR.

**Comment by sibiryakov** [comment]
Overall it looks good!
Regarding your S3 test, I do agree with adding mock and boto. However, would it be possible to make the mocking part read better? I find so many indents hard to read.

**Comment by voith** [comment]
The tests were failing due to issue: https://github.com/travis-ci/travis-ci/issues/5246. So I had to follow the suggestion given here: https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882. 

The actual fix was proposed here: https://github.com/GoogleCloudPlatform/compute-image-packages/pull/213. As per [comment](https://github.com/GoogleCloudPlatform/compute-image-packages/pull/213#issuecomment-230328961) it seems that the issue has been fixed but ubuntu has yet to update its images. Hence the tests were failing on travis.

Sadly, I had to modify `tox.ini`. But thats the only work around for getting this work. If we are merging this PR, than we need to create an issue to keep track if the ubuntu images have been updated with the fix, so that we can get rid of this unnecessary code.

**Comment by sibiryakov** [comment]
Sure @voith let's create an issue!

**Comment by sibiryakov** [comment]
Thank you 🍺

**Comment by voith** [comment]
created issue #213 as per https://github.com/scrapinghub/frontera/pull/208#issuecomment-251701602

**Pull request merged**
